name: textlint
on: 
  pull_request_target:
    types: [ opened, synchronize ]
    paths: [ 'blog/**/*.md' ]
jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx textlint *.md >> ./.textlint.log
      - run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
